/* topology.h — CPU topology generated by external script (simulated)
 *
 * 硬编码的系统拓扑：2 NUMA 节点 x 4 groups x 4 核 = 32 核
 */

#ifndef TOPOLOGY_H
#define TOPOLOGY_H

#define NUM_NODES            2
#define NUM_GROUPS           32
#define MAX_CORES_PER_GROUP  16
#define MAX_OS_CPU           256

struct CoreGroup {
    int group_id;
    int node_id;
    int num_cores;                     /* 总核心数（静态） */
    int free_count;                    /* 空闲核心数（运行时，初始=num_cores） */
    int os_cpus[MAX_CORES_PER_GROUP];
};

struct NodeInfo {
    int node_id;
    int num_groups;
    int num_cores;                     /* 总核心数（静态） */
    int free_count;                    /* 运行时，=该节点所有组的 free_count 之和 */
    int group_ids[16];
};

struct Topology {
    int num_nodes;
    int num_groups;
    struct CoreGroup groups[NUM_GROUPS];
    struct NodeInfo nodes[NUM_NODES];
};

/* ---- 硬编码拓扑实例 -----------------------------------------------
 * 使用条件编译，仅在定义 TOPOLOGY_IMPLEMENTATION 的编译单元中生成。
 * cpu_bind.c 定义该宏，test_cpu_bind.c 不定义（通过 extern 链接）。
 *
 * 拓扑结构：
 *   Node 0 (16 核) —— groups 0~3, 每组 4 核 {0..3, 4..7, 8..11, 12..15}
 *   Node 1 (16 核) —— groups 4~7, 每组 4 核 {16..19, 20..23, 24..27, 28..31}
 */

#ifdef TOPOLOGY_IMPLEMENTATION

struct Topology sys_topology = {
    .num_nodes  = 2,
    .num_groups = 8,

    .groups = {
        [0] = { .group_id = 0, .node_id = 0, .num_cores = 4, .free_count = 4,
                .os_cpus = { 0,  1,  2,  3 } },
        [1] = { .group_id = 1, .node_id = 0, .num_cores = 4, .free_count = 4,
                .os_cpus = { 4,  5,  6,  7 } },
        [2] = { .group_id = 2, .node_id = 0, .num_cores = 4, .free_count = 4,
                .os_cpus = { 8,  9, 10, 11 } },
        [3] = { .group_id = 3, .node_id = 0, .num_cores = 4, .free_count = 4,
                .os_cpus = {12, 13, 14, 15} },
        [4] = { .group_id = 4, .node_id = 1, .num_cores = 4, .free_count = 4,
                .os_cpus = {16, 17, 18, 19} },
        [5] = { .group_id = 5, .node_id = 1, .num_cores = 4, .free_count = 4,
                .os_cpus = {20, 21, 22, 23} },
        [6] = { .group_id = 6, .node_id = 1, .num_cores = 4, .free_count = 4,
                .os_cpus = {24, 25, 26, 27} },
        [7] = { .group_id = 7, .node_id = 1, .num_cores = 4, .free_count = 4,
                .os_cpus = {28, 29, 30, 31} },
    },

    .nodes = {
        [0] = { .node_id = 0, .num_groups = 4, .num_cores = 16, .free_count = 16,
                .group_ids = {0, 1, 2, 3} },
        [1] = { .node_id = 1, .num_groups = 4, .num_cores = 16, .free_count = 16,
                .group_ids = {4, 5, 6, 7} },
    },
};

#endif /* TOPOLOGY_IMPLEMENTATION */

#endif /* TOPOLOGY_H */
